import type { Presentation } from "./types";

export const initialPresentations: Presentation[] = [
  {
    id: "quiet-launch",
    title: "Quiet launch strategy",
    updated: "12 min ago",
    goal: "Align the product team around a focused launch plan.",
    audience: "Product and go-to-market leads",
    durationMinutes: 8,
    progress: 86,
    slides: [
      {
        id: "q1",
        eyebrow: "OPENING",
        title: "A quieter way to launch",
        body: "Most launches compete for attention. Ours is designed to earn trust. Today, I’ll walk through a focused plan that starts with our strongest users, learns quickly, and scales only when the signal is clear.",
        cue: "Pause after ‘earn trust.’ Let the contrast land.",
        cueType: "Pause",
        duration: "0:52",
        marker: "Calm opening",
        accent: "petal",
      },
      {
        id: "q2",
        eyebrow: "THE SIGNAL",
        title: "Clarity is already compounding",
        body: "In the last six weeks, activation moved from sixty-one to seventy-four percent. The change was not driven by more traffic. It came from making the first ten minutes of the product easier to understand.",
        cue: "Point to 74%, then return your attention to the room.",
        cueType: "Gesture",
        duration: "1:08",
        marker: "Anchor the metric",
        accent: "blue",
      },
      {
        id: "q3",
        eyebrow: "THE PLAN",
        title: "Three deliberate moves",
        body: "The plan is intentionally small. First, invite the users who already feel the problem most sharply. Second, give them a guided first week. Third, use what we learn to shape the public story.",
        cue: "Count the three moves on your fingers—slowly.",
        cueType: "Gesture",
        duration: "1:14",
        marker: "Three beats",
        accent: "ink",
      },
      {
        id: "q4",
        eyebrow: "CLOSE",
        title: "The ask",
        body: "I’m asking for one focused month, one shared measure of success, and permission to learn before we amplify. If we protect that focus, the public launch will have a stronger story because it will be true.",
        cue: "Look up for the final sentence. Do not rush the ask.",
        cueType: "Look up",
        duration: "0:58",
        marker: "Direct close",
        accent: "petal",
      },
    ],
  },
  {
    id: "research-review",
    title: "Research review",
    updated: "Yesterday",
    goal: "Explain the research findings without losing the non-technical audience.",
    audience: "Faculty partners and program leads",
    durationMinutes: 12,
    progress: 54,
    slides: [
      {
        id: "r1",
        eyebrow: "CONTEXT",
        title: "What we wanted to understand",
        body: "We started with one practical question: what helps a new learner stay engaged after the first moment of difficulty? The data points toward a surprisingly human answer—timely reassurance matters as much as instructional clarity.",
        cue: "Slow down on the research question.",
        cueType: "Emphasize",
        duration: "1:06",
        marker: "Frame the question",
        accent: "blue",
      },
      {
        id: "r2",
        eyebrow: "FINDING",
        title: "Support changes persistence",
        body: "Participants who received a short reassurance cue were more likely to attempt the task again. This does not prove causation on its own, but it gives us a strong direction for the next study.",
        cue: "Emphasize the limitation before the conclusion.",
        cueType: "Emphasize",
        duration: "1:12",
        marker: "State uncertainty",
        accent: "ink",
      },
    ],
  },
  {
    id: "team-update",
    title: "August team update",
    updated: "Aug 24",
    goal: "Give the team a clear view of progress and the next decision.",
    audience: "Internal team",
    durationMinutes: 6,
    progress: 28,
    slides: [
      {
        id: "t1",
        eyebrow: "THIS MONTH",
        title: "Momentum, with one constraint",
        body: "We made meaningful progress this month, especially in onboarding. The constraint is capacity, so the next decision is not what we can add—it is what we can protect.",
        cue: "Pause before naming the constraint.",
        cueType: "Pause",
        duration: "0:46",
        marker: "Set the tension",
        accent: "petal",
      },
    ],
  },
];
